### ISSUE TITLE
Cmake Deployment Failed

### ISSUE THREAD

**Issue by ProgramCX** [L-Super/QClipboard#5]
I want to make commitments to your respository,but cmake deployment failed.
![image](https://github.com/user-attachments/assets/58b0af64-576f-42bb-b8c0-5cd61f9d2fa2)

**Comment by L-Super** [comment]
Thanks for your interest and the desire to contribute! 

It's uses git submodule. So you need to use this command:
```bash
git clone https://github.com/L-Super/QClipboard --recursive
```

**Comment by ProgramCX** [comment]
Ok.I succeed using your command line.

**Comment by ProgramCX** [comment]
我想问问，你用的什么版本qt

**Comment by L-Super** [comment]
> 我想问问，你用的什么版本qt

Qt 5.15.2 and Qt 6.7.0

**Comment by ProgramCX** [comment]
我用的Qt 6.7的qt,由于Qt 6.7 加入了响应式布局
![image](https://github.com/user-attachments/assets/91aaeb5b-7381-4f67-bfee-34cb0071ad52)
和自适应系统主题色，导致你的软件使用Qt 6.7模块界面不是很好。

**Comment by ProgramCX** [comment]
你可以把系统调成深色主题，然后用Qt 6.7模块的编译器编译运行一下。

**Comment by L-Super** [comment]
> 我用的Qt 6.7的qt,由于Qt 6.7 加入了响应式布局
> ![image](https://github.com/user-attachments/assets/91aaeb5b-7381-4f67-bfee-34cb0071ad52)
> 和自适应系统主题色，导致你的软件使用Qt 6.7模块界面不是很好。

这个应该是样式的问题，后续可以增加适应系统主题色的功能

**Comment by ProgramCX** [comment]
好的，我先阅读一下你的代码

**Comment by L-Super** [comment]
欢迎加我WX进一步沟通，WX：Mr-CMS
